"""
pages/8_ML_Signals.py  —  ML Signal Dashboard.

Displays per-symbol buy/hold/sell signals generated by the
RandomForest + Ridge ensemble in utils/ml_signals.py.

Features
--------
  • Summary table: symbol, signal, confidence, F1 (CV), last trained
  • Drill-down: select a symbol to see P(BUY) history and feature importance
  • Runs in parallel across all 50 symbols (ThreadPoolExecutor)
  • Cached: models are stored in SQLite for 24 h (no re-training on re-runs)
"""
from __future__ import annotations

import concurrent.futures

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from utils.constants import NIFTY50
from utils.data import fetch_all_history
from utils.ml_signals import SKLEARN_OK, SignalResult, predict_signals

st.set_page_config(page_title="ML Signals", page_icon="🤖", layout="wide")
st.title("🤖 ML Signal Dashboard")
st.caption(
    "RandomForest + Ridge ensemble • 30 price/volume features • "
    "5-day forward-return labels • Models cached 24 h in SQLite."
)

if not SKLEARN_OK:
    st.error("❌ scikit-learn is not installed. Run `pip install scikit-learn>=1.3`.")
    st.stop()

# ---------------------------------------------------------------------------
# Load history (cached)
# ---------------------------------------------------------------------------
with st.spinner("📡 Loading 5-year history… (first load takes ~30 s)"):
    history = fetch_all_history()

symbols = [s["symbol"] for s in NIFTY50]

# ---------------------------------------------------------------------------
# Run signals in parallel
# ---------------------------------------------------------------------------
@st.cache_data(ttl=3600, show_spinner=False)
def _run_all_signals(sym_list: tuple[str, ...]) -> dict[str, SignalResult]:
    results: dict[str, SignalResult] = {}
    def _worker(sym: str) -> tuple[str, SignalResult]:
        df = history.get(sym)
        if df is None or df.empty:
            return sym, SignalResult(
                symbol=sym, signal="N/A", confidence=0.0,
                feature_imp=pd.Series(dtype=float), last_proba=0.0,
                error="no history",
            )
        return sym, predict_signals(sym, df)

    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as ex:
        for sym, res in ex.map(_worker, sym_list):
            results[sym] = res
    return results

with st.spinner("🤖 Computing ML signals (uses cached models where available)…"):
    signals = _run_all_signals(tuple(symbols))

# ---------------------------------------------------------------------------
# Summary table
# ---------------------------------------------------------------------------
rows = []
for sym, r in signals.items():
    rows.append({
        "Symbol":      sym,
        "Signal":      r.signal,
        "Confidence":  f"{r.confidence:.1%}",
        "P(BUY)": f"{r.last_proba:.3f}",
        "CV F1":       f"{r.f1_cv:.3f}" if r.f1_cv else "—",
        "Trained":     r.trained_at.strftime("%d %b %H:%M") if r.trained_at else "—",
        "Error":       r.error or "",
    })

summary_df = pd.DataFrame(rows)

def _colour_signal(val: str) -> str:
    if val == "BUY":  return "color: #437a22; font-weight:600"
    if val == "SELL": return "color: #a12c7b; font-weight:600"
    return "color: #7a7974"

st.subheader("Signal Summary — All 50 Symbols")
st.dataframe(
    summary_df.style.applymap(_colour_signal, subset=["Signal"]),
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ---------------------------------------------------------------------------
# Drill-down
# ---------------------------------------------------------------------------
st.subheader("Symbol Deep-Dive")
chosen = st.selectbox("Select symbol", symbols)
res    = signals.get(chosen)

if res is None or res.signal == "N/A":
    st.warning(f"No signal available for {chosen}: {getattr(res, 'error', 'unknown')}")
else:
    c1, c2, c3 = st.columns(3)
    colour = {"BUY": "🟢", "SELL": "🔴", "HOLD": "🟡"}.get(res.signal, "⚪")
    c1.metric(f"{colour} Signal",    res.signal)
    c2.metric("Confidence",          f"{res.confidence:.1%}")
    c3.metric("CV F1 Score",         f"{res.f1_cv:.3f}" if res.f1_cv else "—")

    # P(BUY) history
    if not res.history.empty:
        fig_prob = go.Figure(go.Scatter(
            x=res.history.index,
            y=res.history.values,
            mode="lines",
            name="P(BUY)",
            line=dict(color="#01696f", width=1.5),
        ))
        fig_prob.add_hline(y=0.55, line_dash="dot", line_color="#437a22",
                           annotation_text="BUY threshold")
        fig_prob.add_hline(y=0.45, line_dash="dot", line_color="#a12c7b",
                           annotation_text="SELL threshold")
        fig_prob.update_layout(
            title=f"{chosen} — P(BUY) over time",
            height=300,
            margin=dict(t=40, b=10),
            yaxis=dict(range=[0, 1]),
        )
        st.plotly_chart(fig_prob, use_container_width=True)

    # Feature importance
    if not res.feature_imp.empty:
        top10 = res.feature_imp.head(10).reset_index()
        top10.columns = ["Feature", "Importance"]
        fig_imp = px.bar(
            top10, x="Importance", y="Feature", orientation="h",
            title="Top 10 Feature Importances (Random Forest)",
            color="Importance",
            color_continuous_scale=[[0, "#cedcd8"], [1, "#01696f"]],
        )
        fig_imp.update_layout(height=350, margin=dict(t=40, b=10), coloraxis_showscale=False)
        fig_imp.update_yaxes(autorange="reversed")
        st.plotly_chart(fig_imp, use_container_width=True)
